### ISSUE TITLE
set up named anchors for headers in the SKOPE user's guide

### ISSUE THREAD

**Issue by alee** [openskope/SKOPE#38]
It'd be nice to have linkable sections in the SKOPE user's guide, e.g., 

https://www.openskope.org/skope-users-guide#study-area-size-limits

**Comment by kintigh** [comment]
How can we do that? I can put tags in if you tell me what to do or you're welcome to edit the WordPress document too.
Keith

________________________________
Keith Kintigh -- Santa Fe, NM
Professor Emeritus, Archaeology
Arizona State University
________________________________
From: Allen Lee ***@***.***>
Sent: Tuesday, September 13, 2022 4:04:29 PM
To: openskope/SKOPE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [openskope/SKOPE] set up named anchors for headers in the SKOPE user's guide (Issue #38)


It'd be nice to have linkable sections in the SKOPE user's guide, e.g.,

https://www.openskope.org/skope-users-guide#study-area-size-limits<https://urldefense.com/v3/__https://www.openskope.org/skope-users-guide*study-area-size-limits__;Iw!!IKRxdwAv5BmarQ!bPyAZvMq7VkCmFa1F7KdqKwhyp2jzK-4mziTBjelXRRlMg_fJCc76q1ksGpE5xQ_u-wU-B33dZCVYydkaMa5zQk$>

**Comment by alee** [comment]
I filled in most of them, but for future posterity you can do that by opening up the `Advanced` sidebar on the right in WP and adding an HTML Anchor to a given section: https://wordpress.com/support/splitting-content/page-jumps/

**Comment by kintigh** [comment]
Thank you.  Just let me know if you’d like me to do anything.
Keith


__________________________________________________
Keith Kintigh,<https://www.public.asu.edu/~kintigh/> Professor Emeritus of Archaeology    ASU Directory<https://webapp4.asu.edu/directory/person/56433>
SHESC<http://shesc.asu.edu/>, Arizona State University<http://asu.edu/>, Tempe, AZ USA       tDAR<http://tdar.org/>      CfAS<http://archsynth.org/>
